### ISSUE TITLE
Questions about DriftPHP

### ISSUE THREAD

**Issue by enumag** [driftphp/driftphp#1]
Hi. I just noticed your framework which seems pretty interesting so I'd like to ask some questions.

I'm currently in the middle of refactoring my Symfony-based project to async environment. However I have chosen [Amp](https://amphp.org/) instead of ReactPHP so I won't be using DriftPHP directly. (Real shame that you didn't base it on Amp, imo it's much better than React. I'd love to contribute to an Amp-based framework.) Still though we're in the same asynchronous boat so figured I could learn something here and share my own experience if you're interested. So I went ahead and read some parts of your docs.

----

My first question is about [Controllers](https://driftphp.io/#/?id=controllers). In the docs you wrote:

```
Non-blocking operations are always optional, so if you build your domain blocking, this is going to work as well.
```

Wouldn't a blocking domain cause the same problem as using regular PHP filesystem functions instead of React Filesystem? [Here](https://driftphp.io/#/?id=filesystem) you strongly discourage using blocking filesystem functions. **So why is it not a problem in a controller?**

----

Next I'd like to ask about your [Twig adapter](https://driftphp.io/#/?id=twig-adapter). As far as I know Twig is using normal PHP blocking filesystem functions when working with the templates. Why is that not an issue for you?

----

Lastly I'm currently in the process of refactoring my Security layer. Symfony Security component relies heavily on the global `TokenStorage` service which ofc won't work when handling multiple requests at once. Currently there isn't any Security layer in DriftPHP so I'd like to ask if you've dived into this and can give me some advice how to handle authentication and authorization.

----

EDIT: And one more... why did you choose ReactPHP over Amp? Not trying to criticize your decision or anything, just curious about your reasons. ;-)

----

Thanks and best of luck with your project!

**Comment by mmoreram** [comment]
Hello @enumag !
Thanks so much for that question :D I appreciate the interest!
Let's do it!

---

Absolutely. I will fix this. Blocking code is not an option when working with DriftPHP. A single blocking operation will block the whole thread, so yes. Thanks for reaching me about this.

---

DriftPHP has a Twig component. You're right, Twig uses blocking filesystem operations, but if you take a look you will see that, even if we use `file_get_contents`, we use it before the socket is created. ReactPHP allows regular PHP operations, and because it blocks the whole thread, we should do it before the concurrency is applied. This is why we created a new kernel event called `kernel.preload`, and we simply preload everything inside the kernel before the first request is handled by the web socket.

---

This is something I haven't started yet, tbh. DriftPHP is not a production ready project, and will be not until the next of the year. Because DriftPHP relies on top of Symfony components and Bundle system, I will take a look at the SecurityBundle and will check if we can rely on it. Otherwise, we will work on the direction of a SecurityBundle approach on top of ReactPHP.

---

Good question.
And simple answer.
- Number of questions to ReactPHP team : dozens. Percentage of responses from the ReactPHP team: 100%
- Number of questions to AMP team: around 10. Percentage of responses from the AMP team: 0%.

Building a FW needs tops of support from the base team. It is so important. Without their support, you can not build anything on top of anything. ReactPHP team have been supporting my work since the first day, and all questions had responses. Unpayable attitude.

**Added**

Do not misunderstand me. The main reason why I started using ReactPHP is because there was a good integration with the Symfony kernel by using PHP-PM. Discovering a tech like that is a hard word, and understanding the bases and the fundamental theoretical part is even harder. The library is just amazing and needs tons of pushing from the community. Maybe AMP is better, I don't know and I'm not really interested in this perspective. I'm sure that the PHP community can really learn so much from both, so, in the end, both decisions could be the best.

**Comment by enumag** [comment]
Clever solution with Twig! Thanks for sharing. My application is an API so I won't really need to use it. I'm using Twig to generate PDF files but since converting HTML to PDF can take some time I extracted it to separate process anyway.

Pretty sure you won't be able to rely on Symfony SecurityBundle but ping me when you get to it (if you will remember me). I'll be interested to see what you come up with for sure.

Hmm... so far I had pretty good experience with Amp team. They did help me several times already and I contributed some documentation fixes to them. I do admit it's not 100% though - there is one important [issue](https://github.com/amphp/parallel/issues/93) where they don't react so far.

**Comment by mmoreram** [comment]
Thanks @enumag :)

**Comment by enumag** [comment]
Thanks to you! I'll keep an eye on this project. Ping me in case you have something interesting or want my input on anything. I'll be happy to give you my opinion.

Since Amp can work just fine with React promises I might be able to use some of your work and contribute.

Good luck!

**Comment by mmoreram** [comment]
I think that [LoopRun Barcelona](https://loop-run.io) is a great place for discussion, don't you think? :D

**Comment by enumag** [comment]
I'm considering it though it is a bit far away for me. In case I don't make it, are there going to be video recordings from the conference available?

**Comment by mmoreram** [comment]
I'm working on that, but I cannot ensure it :(

**Comment by enumag** [comment]
I see. Please try, I always feel very sad when I find out about some interesting past talk only to see that the only thing available are the slides. Having these talks available could help to spread async PHP. I really hope you'll be able to make it happen.
